language: ruby

cache: bundler

rvm:
  - 2.2
  - 2.3.3
  - 2.4.0
  - jruby-9

script:
  - bundle exec rake
  - bundle exec danger

notifications:
  email: false
  webhooks:
    urls:
      secure: F8ECoiEAmcEvw3rC/BtacmqhCfc+uAn8WhwH0ockorPdWIbOihnxGz8C3QIz+Cl8QTAuG9hY5lp/VG5UfpX0XirhuJ1FH9AmIUYnIWkWois6UKyjmBV4VitQDtGAkFzK7hCLZjrAT9PBpeJKkljltRgGQaeMDLpasxzgGO8MlcKe6hoZP6AoUdesOu10kePl6eQN4jXkg0Cr9BrYq93tZuCKvKkkVbTgeyni5RjxfMVyARGsu5+OWcMjMmaTYzs1+FNb+d7odvzMaIpJywS/MKAyE3QmXi2QFTb6ij/A77Z7Cj3MzWSD8MvVQdRfOBNfUhWYQzvaD79JR2ijYajxvcrZN/3gpi8CemKrMrqlPmDtRn/mcY3+37U/wfZfJIfhEYnQDkxR+OszaE2abbI0yYC4xQGySnHMltFkALxIdoPixir/OsO/KgDPMtuuQ2zG9d9xHp0rgeW6MEF99pOHNvCSxdny/p57GyFwKtAf+y37RwegTw6V3SU4hyfiofnndDGWX9F19TrFWwNFd9c2oPOkGdNqUahitEzmkQBFZQ76UPNLX9k1k/dzm0RLW8l1Ypa7J2B/aW6WNOT6Ucz0LvNCIte8svtyRgi60emy1r7uL1ltZ7lafP4eLQnWzyBClW7yTkU4F5AcrQFVuGuaq6up5wYfbIK9RU7ocbsOo10=
